language: ruby
sudo: false
cache: bundler
script: 'bundle exec rake test:coverage --trace'
before_install:
  - gem install bundler
  - gem update bundler
rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-9.0.5.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
    - rvm: jruby-head
